### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by cnk113** [PoolLab/generecovery#1]
Hello,

I'd like to run this for my annotations, I was wondering when the code will be released?
Also have you tested how it affects the multimapping quantification in STARSolo (mainly EM based)?

Best,
Chang

**Comment by JBreunig** [comment]
> Hello,
> 
> I'd like to run this for my annotations, I was wondering when the code will be released? Also have you tested how it affects the multimapping quantification in STARSolo (mainly EM based)?
> 
> Best, Chang

I'm curious about EM multimapping as well.

**Comment by PoolLab** [comment]
The code is up! Regarding STARsolo's recovery options for multimapping reads then running your analysis with this parameter will not hurt. With the optimized references you will get the true count for fixed loci so there is no need to rely on the assumption of the EM algorithm. However, for loci where resolving overlaps was not feasible, this mode will help. Also, if you run STARsolo in pre-mRNA mode (--soloFeatures GeneFull), then recovering multimapping reads (--soloMultiMappers EM) will be beneficial as you would otherwise lose reads from overlapping introns. I have not extensively tested that with STARsolo but most likely you will benefit from taking advantage of this feature with the optimized references.

**Comment by cnk113** [comment]
I noticed on the code that the BAM file is required for the optimization, I was wondering what the strategy would be if you had multiple 10x runs from different tissue areas/disease states?

Also have you tried using the STARSolo BAM files as input rather than only the CellRanger BAM file?

**Comment by PoolLab** [comment]
With multiple bam files you should be able to just import and concatenate reads (rbind(a, b) the resulting dataframes after importing with GenomicAlignments package in R). For genome annotation optimization I would highly recommend using Cell Ranger aligned bam files as Cell Ranger very clearly classifies reads according to whether they are exonic, intronic or intergenic (can retrieve from RE tag from bam file, RE=E, RE=N and RE=I respectively). With STARsolo BAM files it's much more of a hassle to pull out a specific class of aligned reads.
