### ISSUE TITLE
1_Annotation pre-processing.R error

### ISSUE THREAD

**Issue by khandaud15** [PoolLab/generecovery#2]
Hi, 

I am getting this weird error while running your script on our dataset to recover missing genes

at this line of the code, 
> ga_seq_data = as(gr_seq_data, "GAlignments")
Error in validObject(.Object) : invalid class “GAlignments” object: 
    'x@cigar' is not parallel to 'x'

I am getting this error, 

can you please let me know, whats going wrong here. I have provided gene.gtf file from our cellrnager run as well as bam and bai file.

Thanks

Daud

**Comment by PoolLab** [comment]
We were not able to reproduce the error but please do forward a link to your bam and bai files and we will try to reproduce it. I suspect it might be due to GenomicAlignments library not being loaded, which explains why "GAlignments" is reported as invalid class. Alternatively I would recommend trying to rerun the updated current version of the code ("1_Annotation pre-processing.R") which should run with no issues.
